### ISSUE TITLE
cannot run on a wine64 windows 10

### ISSUE THREAD

**Issue by xevilstar** [PietJankbal/Chocolatey-for-wine#10]
Dear mantainer

I have downloaded the ChoCinstaller_0.5o.703.exe

it crashes

0198:fixme:ntdll:WinSqmIsOptedIn (): stub
0198:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0000000002D2E368, 34) stub
0198:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0000000002D23B28, 17) stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:RtlGetCurrentProcessorNumberEx (000000000019D480) :semi-stub
0198:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0000000002D29FC0, 40) stub
0198:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0000000002D25008, 51) stub
0198:fixme:nls:get_dummy_preferred_ui_language (0x8 0x409 000000000019E9C0 0000000000000000 000000000019E9B8) returning a dummy value (current locale)
0198:fixme:nls:get_dummy_preferred_ui_language (0x8 0x409 000000000019E9C0 000000000019E910 000000000019E9B8) returning a dummy value (current locale)
01b0:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0000000002D2A218, 38) stub
01b0:fixme:amsi:AmsiInitialize L"PowerShell_C:\\Program Files\\Powershell\\7\\pwsh.exe_7.3.0 SHA: 2c1b3296a1a545d1aa66605c25068c648d664651", 00000000682AE758
01b0:fixme:amsi:AmsiOpenSession 00000000DEADBEEF, 00000000682AE760
0198:fixme:ntdll:EtwEventActivityIdControl 0x1, 000000000019E978: stub
0198:err:seh:NtRaiseException Unhandled exception code c0000409 flags 1 addr 0x17a03ad

thanks for your time

**Comment by PietJankbal** [comment]
Hi there,

It seems to me you try to install in  a prefix where already Powershell 7.3.0 is installed according to this message: 
01b0:fixme:amsi:AmsiInitialize L"PowerShell_C:\Program Files\Powershell\7\pwsh.exe_7.3.0

Is that correct?

Please try install on a new fresh prefix. Powershell versions higher then 7.1.5. do not run in wine due to wine-bug https://bugs.winehq.org/show_bug.cgi?id=52396

( Or try wine-staging where there's a fix for this bug)

Regards

**Comment by xevilstar** [comment]
Dear Maintainer
![Screenshot from 2023-01-29 09-48-50](https://user-images.githubusercontent.com/1389525/215315564-3703980f-a3e9-427f-8b78-5a813d46cdbf.png)
I have followed your instructions 
please take a look at the attached screenshot

Thanks for your time

**Comment by xevilstar** [comment]
thanks all issues fixed
