### ISSUE TITLE
Get-FileHash support in ps51

### ISSUE THREAD

**Issue by Lignar** [PietJankbal/Chocolatey-for-wine#14]
Hi, is it possible to add [Get-FileHash](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-filehash?view=powershell-5.1) term support in ps51? It works fine in PowerShell Core, but when invoked in ps51 it returns:
```
PS 51! C:\ConEmu $ get-filehash .\ConEmu.exe
get-filehash : The term 'get-filehash' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ get-filehash .\ConEmu.exe
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (get-filehash:String) [], Comman
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by Lignar** [comment]
Never mind, turns out for my use case adding ps51_ise was enough to get things running. ps51 still can't call get-filehash, but the app that requires both ps5 and this term somehow works fine.

**Comment by PietJankbal** [comment]
Hi, thanks for the bugreport.

I've updated winetricks.ps1 script so Get-FileHash should now work in ps51 as well (https://github.com/PietJankbal/Chocolatey-for-wine/commit/9a7b688aa446becbfdd14b8de6baefea355b9dd9)

For now if you'd like to use updated winetricks script (https://github.com/PietJankbal/Chocolatey-for-wine/blob/main/winetricks.ps1) you could copy it over the the existing c:\ProgramData\chocolatey\winetricks.ps1

Regards

**Comment by PietJankbal** [comment]
This has been fixed in latest releases. Thanks for the bugreport

Regards
