### ISSUE TITLE
Add choco pin add -n chocolatey so it doesn't update to v2 and break

### ISSUE THREAD

**Issue by Git-North** [PietJankbal/Chocolatey-for-wine#15]
Adding the pin command will mean that chocolatey will not update when using all and not break itself
adding it to the setup script might be useful
`choco pin add -n chocolatey`

**Comment by PietJankbal** [comment]
Hi, thanks for the issue.

I've added it to the script for next release: 
https://github.com/PietJankbal/Chocolatey-for-wine/commit/91dc803478524dcc0c155dd15c2df4e15021ff6a

**Comment by PietJankbal** [comment]
this was fixed a time ago. thanks for the bugreport.
