### ISSUE TITLE
Running on headless ubuntu-server

### ISSUE THREAD

**Issue by Lukium** [PietJankbal/Chocolatey-for-wine#19]
Hi, I'm the developer for https://github.com/lukium/palworld-admin

I'm trying to support running the application via Wine, and all that's left to get it working right is to be able to run powershell in Wine. I was able to successfully use your implementation in ubuntu desktop, but can't seem to get it working on ubuntu-server using xvfb-run wine as I get:

lukium@linux-23-10-test:~/palworld-admin-wine/Chocolatey-for-wine$ WINEARCH=win32 WINEPREFIX=~/.wine32 xvfb-run wine ./install_pwshwrapper.exe.
Application could not be started, or no application associated with the specified file.

I have also tried on a 64bit prefix with the same result.

Would you kindly try to help me get this working? It's really so close :)

**Comment by Lukium** [comment]
> Reference

I figured out what to do :)

I wrote my own wrapper in C# both for x86 and x64 that I can drop in place of

x86 - $HOME/.wine/drive_c/windows/system32/WindowsPowerShell/v1.0/powershell.exe
x64 - $HOME/.wine/drive_c/windows/syswow64/WindowsPowerShell/v1.0/powershell.exe

And the wrapper redirects all commands to:
$HOME/.wine/drive_c/'Program Files'/Powershell/7/pwsh.exe

And returns back the output.

You can check it out at
https://github.com/Lukium/powershell-wine-wrapper

Your wrapper was definitely the inspiration for the idea though, so thanks!

**Comment by PietJankbal** [comment]
Hi, ok, then I close this issue. Nice job btw! 

A last remark: to improve you wrapper you might (just as in my code) want to add some code to insert a "-c" if the arguments don't contain it.
One difference between powershell and pwsh is that powershell doesn't require that "-c" so 'wine powershell -nologo 1+2' is a valid command, and it will fail if you just pass it to pwsh (it should change into 'pwsh -nologo -c 1+2'). But if your program doesn't need it I guess this is just optional.

**Comment by PietJankbal** [comment]
closed
