### ISSUE TITLE
Not working with wine-7.8

### ISSUE THREAD

**Issue by Schroedingers-Cat** [PietJankbal/Chocolatey-for-wine#3]
v0.1.703 and v0.0.703 both don't work with wine 7.8 (tk-glitch build using "Bottles" as prefix manager). v0.0.703 works fine with wine 7.7 (tk-glitch build using "Bottles"), so I guess it's an incompatibility with wine 7.8. The terminal will quit suddenly at the last line:
```
WINEPREFIX="~/.local/share/bottles/bottles/SimpleVSTs/" wine ~/.local/share/bottles/bottles/SimpleVSTs/drive_c/users/username/Chocolatey-for-wine/ChoCinstaller_0.1.703.exe
fsync: up and running.
002c:fixme:winediag:LdrInitializeThunk Wine TkG (staging) 7.8 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (126).

Downloading PowerShell-7.0.3-win-x64.msi

0110:fixme:urlmon:InternetBindInfo_GetBindString not supported string type 20
0110:fixme:urlmon:DownloadBSC_OnProgress Unsupported status 3
0110:fixme:urlmon:DownloadBSC_OnStopBinding CopyFile failed: 3
```

**Comment by PietJankbal** [comment]
Hi, I only have a self-compiled tk-glitch (7.8) , and for me it works fine, so I can only guess atm.

 Google says error 3 is ERROR_PATH_NOT_FOUND. 
Maybe it cannot find the path to your TEMP directory? Could you check if the downloaded msi file is present in ~/.wine/drive_c/users/your_name/TEMP.
And what does  'wine cmd /c echo "%TEMP%" '  say?

**Comment by Schroedingers-Cat** [comment]
My bad, I must have deleted the "TEMP" directory in my user directory every time I tried it.
Having the TEMP directory there fixes the problem. Thanks a lot!
