### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by provokateurin** [PietJankbal/Chocolatey-for-wine#6]
In a fresh prefix I always get:
```log
MethodInvocationException: Z:\home\jld3103\Downloads\Chocolatey-for-wine\choc_install.ps1:335
Line |
 335 |  . ip.org/a/7z2201-x64.exe', $(Join-Path "$env:TEMP" '7z2201-x64.exe') )
     |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "DownloadFile" with "2" argument(s): "Unknown error (0x273f) Unknown error (0x273f)"

034c:fixme:amsi:AmsiScanBuffer 00000000DEADBEEF, 0000000003B714FC, 78, L"", 00000000DEADBEEF, 0000000022D6DFD8
C:\users\jld3103\Temp\7z2201-x64.exe: The term 'C:\users\jld3103\Temp\7z2201-x64.exe' is not recognized as the name of a 
cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
I looked and the file doesn't exist in that folder, so I'm not sure if the problem was that it couldn't be execute or that it doesn't exist.

I'm running wine-7.15 (Staging). Same problem happens on wine-7.15 and wine-7.0.

**Comment by jld3103** [comment]
I commented the DownloadFile line and manually downloaded the file to the directory and it did get further, but then it fails on other DownloadFile calls. Error message is always the same. Not sure what the problem is. Let me know what info you need to debug this.

**Comment by PietJankbal** [comment]
Hi jld3103, that error (0x273f= WSAEAFNOSUPPORT) seems to be "An address incompatible with the requested protocol was used." 

Unfortunately I don't really know anything about this socket /protocol stuff.

Just to be sure: when you do 'wine powershell' and then manually paste it
 (New-Object System.Net.WebClient).DownloadFile('https://d3.7-zip.org/a/7z2201-x64.exe', $(Join-Path "$env:TEMP" '7z2201-x64.exe') )

it doesn't work either (it won`t get downloaded i mean)?

The only thing I could think of is some firewall or so you have installed? But that's just shooting in the dark. 

Maybe you could try if earlier release https://github.com/PietJankbal/Chocolatey-for-wine/releases/tag/v0.3.703 does work?  Do you get the same error then ?

**Comment by PietJankbal** [comment]
As there`s no response i gonna close it. Reopen if you still encounter this bug

**Comment by PietJankbal** [comment]
cannot reproduce
