### ISSUE TITLE
The exe installer fail message needs to be specific, not generic bla.

### ISSUE THREAD

**Issue by rwperrott** [PietJankbal/Chocolatey-for-wine#7]
This is pretty much the classic error message antipattern.

Each different fail should specify specifically what failed, not just goto failed:
```c
failed:
    fprintf( stderr, "Something went wrong :( (32-bit?, winversion <win7?, failing download? ....  \n" );
    return 0; /* fake success anyway */
```
If I can, I'll recompile mainv1.c with my fixes for this, so that I have some chance to identify the specific cause of the failure(s).

**Comment by PietJankbal** [comment]
Hi,

thanks for the message. I really didn't pay any attention to those fail messages as it hardly ever fails for me ;)
Note: the 32 bit fail messages probably do not make any sense as the installer is compiled as 64-bit, and cannot be run anyway on WINEARCH=win32

**Comment by PietJankbal** [comment]
Hi, I changed code and made fail message more specific in places where I think it is needed. Hence marking this as fixed
