### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by Schroedingers-Cat** [PietJankbal/Chocolatey-for-wine#8]
I'm unable to find any information about how to update an existing wineprefix with an older version of this project. There's some info in the notes section of README.md:
```
Do NOT use on existing wineprefix [...]
```
This hints at it being impossible to update chocolatey-for-wine and it seems to be a requirement to start the wineprefix from scratch whenever a new version is out. If that is the case, it would be good to have that clearly written down in the notes section.  

If it is possible to update an existing prefix, it would be great to have some instructions on how to do that.

**Comment by PietJankbal** [comment]
Hi, sorry for long delay. I`ll have a look at it. I guess it would be possible to upgrade but if you made changes to your profile.ps1 then they will get lost. I'll do some testing and change instructions accordingly. to be continued

**Comment by PietJankbal** [comment]
Hi, I added a remark that updating is not (yet) supported. As this is really difficult to do when changes in choc_install.ps1 are made. Maybe in future I'll give it another try. For now I'm closing this issue as I updated the README with this info. Thanks for the report
