### ISSUE TITLE
cannot find the exe for download and cannot compile

### ISSUE THREAD

**Issue by xevilstar** [PietJankbal/Chocolatey-for-wine#9]
Chocolatey-for-wine$ winegcc-development -municode  -mconsole mainv1.c -lurlmon -lshlwapi -s -o ChoCinstaller_0.5i.703.exe
mainv1.c: In function 'is_single_or_last_option':
mainv1.c:32:19: warning: implicit declaration of function '_wcsnicmp' [-Wimplicit-function-declaration]
   32 |     return ( ( ( !_wcsnicmp( opt, L"-c", 2 ) && _wcsnicmp( opt, L"-config", 7 ) ) || !_wcsnicmp( opt, L"-n", 2 ) || !_wcsnicmp( opt, L"-enc", 4 ) ||\
      |                   ^~~~~~~~~
mainv1.c:33:82: warning: implicit declaration of function 'wcscmp' [-Wimplicit-function-declaration]
   33 |                  !_wcsnicmp( opt, L"-m", 2 ) || !_wcsnicmp( opt, L"-s", 2 )  || !wcscmp( opt, L"-" ) || !_wcsnicmp( opt, L"-f", 2 ) ) ? TRUE : FALSE );
      |                                                                                  ^~~~~~
mainv1.c: In function 'wmain':
mainv1.c:96:5: warning: implicit declaration of function 'wcscat' [-Wimplicit-function-declaration]
   96 |     wcscat(conemu_pathW, L"\\ConEmu\\ConEmu64.exe");
      |     ^~~~~~
mainv1.c:99:18: warning: implicit declaration of function 'wcsrchr' [-Wimplicit-function-declaration]
   99 |     filenameW =  wcsrchr( filepathW, '\\') + 1;
      |                  ^~~~~~~
mainv1.c:99:15: warning: assignment to 'wchar_t *' {aka 'short unsigned int *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
   99 |     filenameW =  wcsrchr( filepathW, '\\') + 1;
      |               ^
mainv1.c:103:11: warning: implicit declaration of function 'wcsncmp' [-Wimplicit-function-declaration]
  103 |     if ( !wcsncmp( filenameW , L"ChoCinstaller_" , 14 ) )
      |           ^~~~~~~
mainv1.c:109:34: warning: passing argument 2 of 'CopyFileW' makes pointer from integer without a cast [-Wint-conversion]
  109 |        if ( !CopyFileW( argv[0], wcscat(ps_pathW, L"\\system32\\WindowsPowershell\\v1.0\\powershell.exe" ), FALSE) ) goto failed;
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                  |
      |                                  int
In file included from /usr/include/wine-development/wine/windows/windows.h:39,
                 from mainv1.c:26:
/usr/include/wine-development/wine/windows/winbase.h:1864:49: note: expected 'LPCWSTR' {aka 'const short unsigned int *'} but argument is of type 'int'
 1864 | WINBASEAPI BOOL        WINAPI CopyFileW(LPCWSTR,LPCWSTR,BOOL);
      |                                                 ^~~~~~~
mainv1.c:110:8: warning: implicit declaration of function 'wcscpy' [-Wimplicit-function-declaration]
  110 |        wcscpy( setup_pathW, argv[0] );
      |        ^~~~~~
mainv1.c:115:24: warning: passing argument 1 of 'CopyFileW' makes pointer from integer without a cast [-Wint-conversion]
  115 |        if( !CopyFileW( wcscat( setup_pathW, L"\\powershell32.exe" ), wcscat( ps_pathW, L"\\syswow64\\WindowsPowershell\\v1.0\\powershell.exe" ), FALSE) ) goto failed;
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                        |
      |                        int
/usr/include/wine-development/wine/windows/winbase.h:1864:41: note: expected 'LPCWSTR' {aka 'const short unsigned int *'} but argument is of type 'int'
 1864 | WINBASEAPI BOOL        WINAPI CopyFileW(LPCWSTR,LPCWSTR,BOOL);
      |                                         ^~~~~~~
mainv1.c:115:70: warning: passing argument 2 of 'CopyFileW' makes pointer from integer without a cast [-Wint-conversion]
  115 |        if( !CopyFileW( wcscat( setup_pathW, L"\\powershell32.exe" ), wcscat( ps_pathW, L"\\syswow64\\WindowsPowershell\\v1.0\\powershell.exe" ), FALSE) ) goto failed;
      |                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                      |
      |                                                                      int
/usr/include/wine-development/wine/windows/winbase.h:1864:49: note: expected 'LPCWSTR' {aka 'const short unsigned int *'} but argument is of type 'int'
 1864 | WINBASEAPI BOOL        WINAPI CopyFileW(LPCWSTR,LPCWSTR,BOOL);
      |                                                 ^~~~~~~
mainv1.c:124:35: warning: passing argument 2 of 'CopyFileW' makes pointer from integer without a cast [-Wint-conversion]
  124 |         if ( !CopyFileW( cacheW , wcscat( tmpW, msiW ), FALSE ) )
      |                                   ^~~~~~~~~~~~~~~~~~~~
      |                                   |
      |                                   int
/usr/include/wine-development/wine/windows/winbase.h:1864:49: note: expected 'LPCWSTR' {aka 'const short unsigned int *'} but argument is of type 'int'
 1864 | WINBASEAPI BOOL        WINAPI CopyFileW(LPCWSTR,LPCWSTR,BOOL);
      |                                                 ^~~~~~~
mainv1.c:127:43: warning: passing argument 2 of 'URLDownloadToFileW' makes pointer from integer without a cast [-Wint-conversion]
  127 |             if( URLDownloadToFileW( NULL, wcscat( wcscat( wcscat ( wcscat ( downloadW, L"https://github.com/PowerShell/PowerShell/releases/download/v" ), versionW) , L"/" ), msiW), tmpW,0 , NULL ) != S_OK )
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                           |
      |                                           int
In file included from /usr/include/wine-development/wine/windows/objbase.h:501,
                 from /usr/include/wine-development/wine/windows/ole2.h:25,
                 from /usr/include/wine-development/wine/windows/wtypes.h:13,
                 from /usr/include/wine-development/wine/windows/winscard.h:22,
                 from /usr/include/wine-development/wine/windows/windows.h:68:
/usr/include/wine-development/wine/windows/urlmon.h:7114:45: note: expected 'LPCWSTR' {aka 'const short unsigned int *'} but argument is of type 'int'
 7114 | HRESULT WINAPI URLDownloadToFileW(LPUNKNOWN,LPCWSTR,LPCWSTR,DWORD,LPBINDSTATUSCALLBACK);
      |                                             ^~~~~~~
mainv1.c:133:24: warning: passing argument 1 of 'CreateProcessW' makes pointer from integer without a cast [-Wint-conversion]
  133 |         CreateProcessW(wcscat( msiexecW, L"\\msiexec.exe" ), wcscat( wcscat( bufW, L" /i " ), wcscat( wcscat( tmpW, msiW ) , L" ENABLE_PSREMOTING=1 REGISTER_MANIFEST=1 /q" ) ), 0, 0, 0, HIGH_PRIORITY_CLASS, 0, 0, &si, &pi);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                        |
      |                        int
/usr/include/wine-development/wine/windows/winbase.h:1922:46: note: expected 'LPCWSTR' {aka 'const short unsigned int *'} but argument is of type 'int'
 1922 | WINBASEAPI BOOL        WINAPI CreateProcessW(LPCWSTR,LPWSTR,LPSECURITY_ATTRIBUTES,LPSECURITY_ATTRIBUTES,BOOL,DWORD,LPVOID,LPCWSTR,LPSTARTUPINFOW,LPPROCESS_INFORMATION);
      |                                              ^~~~~~~
mainv1.c:133:62: warning: passing argument 2 of 'CreateProcessW' makes pointer from integer without a cast [-Wint-conversion]
  133 |         CreateProcessW(wcscat( msiexecW, L"\\msiexec.exe" ), wcscat( wcscat( bufW, L" /i " ), wcscat( wcscat( tmpW, msiW ) , L" ENABLE_PSREMOTING=1 REGISTER_MANIFEST=1 /q" ) ), 0, 0, 0, HIGH_PRIORITY_CLASS, 0, 0, &si, &pi);
      |                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                              |
      |                                                              int
/usr/include/wine-development/wine/windows/winbase.h:1922:54: note: expected 'LPWSTR' {aka 'short unsigned int *'} but argument is of type 'int'
 1922 | WINBASEAPI BOOL        WINAPI CreateProcessW(LPCWSTR,LPWSTR,LPSECURITY_ATTRIBUTES,LPSECURITY_ATTRIBUTES,BOOL,DWORD,LPVOID,LPCWSTR,LPSTARTUPINFOW,LPPROCESS_INFORMATION);
      |                                                      ^~~~~~
mainv1.c:139:37: warning: passing argument 2 of 'CreateProcessW' makes pointer from integer without a cast [-Wint-conversion]
  139 |         CreateProcessW( pwsh_pathW, wcscat ( wcscat( wcscat( wcscat( bufW, L" -file " ), setup_pathW ), L"\\choc_install.ps1 " ), setup_pathW ), 0, 0, 0, HIGH_PRIORITY_CLASS, 0, 0, &si, &pi);
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                     |
      |                                     int
/usr/include/wine-development/wine/windows/winbase.h:1922:54: note: expected 'LPWSTR' {aka 'short unsigned int *'} but argument is of type 'int'
 1922 | WINBASEAPI BOOL        WINAPI CreateProcessW(LPCWSTR,LPWSTR,LPSECURITY_ATTRIBUTES,LPSECURITY_ATTRIBUTES,BOOL,DWORD,LPVOID,LPCWSTR,LPSTARTUPINFOW,LPPROCESS_INFORMATION);
      |                                                      ^~~~~~
mainv1.c:152:36: warning: implicit declaration of function 'wcslen' [-Wimplicit-function-declaration]
  152 |         if ( _wcsnicmp ( &argv[0][ wcslen(argv[0]) - 4 ] , L".exe" , 4 ) ) wcscat( cmdlineW, L".exe" ); /* and add '.exe' if necessary */
      |                                    ^~~~~~
mainv1.c:158:82: warning: implicit declaration of function '_wtoi' [-Wimplicit-function-declaration]
  158 |         return ( GetEnvironmentVariableW( L"QPREXITCODE", bufW, MAX_PATH + 1 ) ? _wtoi( bufW ) : exitcode );
      |                                                                                  ^~~~~
mainv1.c:200:82: warning: pointer/integer type mismatch in conditional expression
  200 |     CreateProcessW( pwsh_pathW, !( (i == argc ) && !read_from_stdin ) ? cmdlineW : wcscat( wcscat ( wcscat( wcscat( wcscat( \
      |                                                                                  ^
/usr/bin/ld: cannot find -lurlmon: No such file or directory
/usr/bin/ld: cannot find -lshlwapi: No such file or directory
/usr/bin/ld: cannot find -ladvapi32: No such file or directory
/usr/bin/ld: cannot find -luser32: No such file or directory
/usr/bin/ld: cannot find -lwinecrt0: No such file or directory
/usr/bin/ld: cannot find -lkernel32: No such file or directory
/usr/bin/ld: cannot find -lntdll: No such file or directory
collect2: error: ld returned 1 exit status
winegcc: /usr/bin/gcc failed

**Comment by xevilstar** [comment]
Chocolatey-for-wine$ winegcc-development -municode  -mconsole mainv1.c -lurlmon -lshlwapi -s -o ChoCinstaller_0.5i.703.exe
mainv1.c: In function 'is_single_or_last_option':
mainv1.c:32:19: warning: implicit declaration of function '_wcsnicmp' [-Wimplicit-function-declaration]
   32 |     return ( ( ( !_wcsnicmp( opt, L"-c", 2 ) && _wcsnicmp( opt, L"-config", 7 ) ) || !_wcsnicmp( opt, L"-n", 2 ) || !_wcsnicmp( opt, L"-enc", 4 ) ||\
      |                   ^~~~~~~~~
mainv1.c:33:82: warning: implicit declaration of function 'wcscmp' [-Wimplicit-function-declaration]
   33 |                  !_wcsnicmp( opt, L"-m", 2 ) || !_wcsnicmp( opt, L"-s", 2 )  || !wcscmp( opt, L"-" ) || !_wcsnicmp( opt, L"-f", 2 ) ) ? TRUE : FALSE );
      |                                                                                  ^~~~~~
mainv1.c: In function 'wmain':
mainv1.c:96:5: warning: implicit declaration of function 'wcscat' [-Wimplicit-function-declaration]
   96 |     wcscat(conemu_pathW, L"\\ConEmu\\ConEmu64.exe");
      |     ^~~~~~
mainv1.c:99:18: warning: implicit declaration of function 'wcsrchr' [-Wimplicit-function-declaration]
   99 |     filenameW =  wcsrchr( filepathW, '\\') + 1;
      |                  ^~~~~~~
mainv1.c:99:15: warning: assignment to 'wchar_t *' {aka 'short unsigned int *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
   99 |     filenameW =  wcsrchr( filepathW, '\\') + 1;
      |               ^
mainv1.c:103:11: warning: implicit declaration of function 'wcsncmp' [-Wimplicit-function-declaration]
  103 |     if ( !wcsncmp( filenameW , L"ChoCinstaller_" , 14 ) )
      |           ^~~~~~~
mainv1.c:109:34: warning: passing argument 2 of 'CopyFileW' makes pointer from integer without a cast [-Wint-conversion]
  109 |        if ( !CopyFileW( argv[0], wcscat(ps_pathW, L"\\system32\\WindowsPowershell\\v1.0\\powershell.exe" ), FALSE) ) goto failed;
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                  |
      |                                  int
In file included from /usr/include/wine-development/wine/windows/windows.h:39,
                 from mainv1.c:26:
/usr/include/wine-development/wine/windows/winbase.h:1864:49: note: expected 'LPCWSTR' {aka 'const short unsigned int *'} but argument is of type 'int'
 1864 | WINBASEAPI BOOL        WINAPI CopyFileW(LPCWSTR,LPCWSTR,BOOL);
      |                                                 ^~~~~~~
mainv1.c:110:8: warning: implicit declaration of function 'wcscpy' [-Wimplicit-function-declaration]
  110 |        wcscpy( setup_pathW, argv[0] );
      |        ^~~~~~
mainv1.c:115:24: warning: passing argument 1 of 'CopyFileW' makes pointer from integer without a cast [-Wint-conversion]
  115 |        if( !CopyFileW( wcscat( setup_pathW, L"\\powershell32.exe" ), wcscat( ps_pathW, L"\\syswow64\\WindowsPowershell\\v1.0\\powershell.exe" ), FALSE) ) goto failed;
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                        |
      |                        int
/usr/include/wine-development/wine/windows/winbase.h:1864:41: note: expected 'LPCWSTR' {aka 'const short unsigned int *'} but argument is of type 'int'
 1864 | WINBASEAPI BOOL        WINAPI CopyFileW(LPCWSTR,LPCWSTR,BOOL);
      |                                         ^~~~~~~
mainv1.c:115:70: warning: passing argument 2 of 'CopyFileW' makes pointer from integer without a cast [-Wint-conversion]
  115 |        if( !CopyFileW( wcscat( setup_pathW, L"\\powershell32.exe" ), wcscat( ps_pathW, L"\\syswow64\\WindowsPowershell\\v1.0\\powershell.exe" ), FALSE) ) goto failed;
      |                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                      |
      |                                                                      int
/usr/include/wine-development/wine/windows/winbase.h:1864:49: note: expected 'LPCWSTR' {aka 'const short unsigned int *'} but argument is of type 'int'
 1864 | WINBASEAPI BOOL        WINAPI CopyFileW(LPCWSTR,LPCWSTR,BOOL);
      |                                                 ^~~~~~~
mainv1.c:124:35: warning: passing argument 2 of 'CopyFileW' makes pointer from integer without a cast [-Wint-conversion]
  124 |         if ( !CopyFileW( cacheW , wcscat( tmpW, msiW ), FALSE ) )
      |                                   ^~~~~~~~~~~~~~~~~~~~
      |                                   |
      |                                   int
/usr/include/wine-development/wine/windows/winbase.h:1864:49: note: expected 'LPCWSTR' {aka 'const short unsigned int *'} but argument is of type 'int'
 1864 | WINBASEAPI BOOL        WINAPI CopyFileW(LPCWSTR,LPCWSTR,BOOL);
      |                                                 ^~~~~~~
mainv1.c:127:43: warning: passing argument 2 of 'URLDownloadToFileW' makes pointer from integer without a cast [-Wint-conversion]
  127 |             if( URLDownloadToFileW( NULL, wcscat( wcscat( wcscat ( wcscat ( downloadW, L"https://github.com/PowerShell/PowerShell/releases/download/v" ), versionW) , L"/" ), msiW), tmpW,0 , NULL ) != S_OK )
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                           |
      |                                           int
In file included from /usr/include/wine-development/wine/windows/objbase.h:501,
                 from /usr/include/wine-development/wine/windows/ole2.h:25,
                 from /usr/include/wine-development/wine/windows/wtypes.h:13,
                 from /usr/include/wine-development/wine/windows/winscard.h:22,
                 from /usr/include/wine-development/wine/windows/windows.h:68:
/usr/include/wine-development/wine/windows/urlmon.h:7114:45: note: expected 'LPCWSTR' {aka 'const short unsigned int *'} but argument is of type 'int'
 7114 | HRESULT WINAPI URLDownloadToFileW(LPUNKNOWN,LPCWSTR,LPCWSTR,DWORD,LPBINDSTATUSCALLBACK);
      |                                             ^~~~~~~
mainv1.c:133:24: warning: passing argument 1 of 'CreateProcessW' makes pointer from integer without a cast [-Wint-conversion]
  133 |         CreateProcessW(wcscat( msiexecW, L"\\msiexec.exe" ), wcscat( wcscat( bufW, L" /i " ), wcscat( wcscat( tmpW, msiW ) , L" ENABLE_PSREMOTING=1 REGISTER_MANIFEST=1 /q" ) ), 0, 0, 0, HIGH_PRIORITY_CLASS, 0, 0, &si, &pi);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                        |
      |                        int
/usr/include/wine-development/wine/windows/winbase.h:1922:46: note: expected 'LPCWSTR' {aka 'const short unsigned int *'} but argument is of type 'int'
 1922 | WINBASEAPI BOOL        WINAPI CreateProcessW(LPCWSTR,LPWSTR,LPSECURITY_ATTRIBUTES,LPSECURITY_ATTRIBUTES,BOOL,DWORD,LPVOID,LPCWSTR,LPSTARTUPINFOW,LPPROCESS_INFORMATION);
      |                                              ^~~~~~~
mainv1.c:133:62: warning: passing argument 2 of 'CreateProcessW' makes pointer from integer without a cast [-Wint-conversion]
  133 |         CreateProcessW(wcscat( msiexecW, L"\\msiexec.exe" ), wcscat( wcscat( bufW, L" /i " ), wcscat( wcscat( tmpW, msiW ) , L" ENABLE_PSREMOTING=1 REGISTER_MANIFEST=1 /q" ) ), 0, 0, 0, HIGH_PRIORITY_CLASS, 0, 0, &si, &pi);
      |                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                              |
      |                                                              int
/usr/include/wine-development/wine/windows/winbase.h:1922:54: note: expected 'LPWSTR' {aka 'short unsigned int *'} but argument is of type 'int'
 1922 | WINBASEAPI BOOL        WINAPI CreateProcessW(LPCWSTR,LPWSTR,LPSECURITY_ATTRIBUTES,LPSECURITY_ATTRIBUTES,BOOL,DWORD,LPVOID,LPCWSTR,LPSTARTUPINFOW,LPPROCESS_INFORMATION);
      |                                                      ^~~~~~
mainv1.c:139:37: warning: passing argument 2 of 'CreateProcessW' makes pointer from integer without a cast [-Wint-conversion]
  139 |         CreateProcessW( pwsh_pathW, wcscat ( wcscat( wcscat( wcscat( bufW, L" -file " ), setup_pathW ), L"\\choc_install.ps1 " ), setup_pathW ), 0, 0, 0, HIGH_PRIORITY_CLASS, 0, 0, &si, &pi);
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                     |
      |                                     int
/usr/include/wine-development/wine/windows/winbase.h:1922:54: note: expected 'LPWSTR' {aka 'short unsigned int *'} but argument is of type 'int'
 1922 | WINBASEAPI BOOL        WINAPI CreateProcessW(LPCWSTR,LPWSTR,LPSECURITY_ATTRIBUTES,LPSECURITY_ATTRIBUTES,BOOL,DWORD,LPVOID,LPCWSTR,LPSTARTUPINFOW,LPPROCESS_INFORMATION);
      |                                                      ^~~~~~
mainv1.c:152:36: warning: implicit declaration of function 'wcslen' [-Wimplicit-function-declaration]
  152 |         if ( _wcsnicmp ( &argv[0][ wcslen(argv[0]) - 4 ] , L".exe" , 4 ) ) wcscat( cmdlineW, L".exe" ); /* and add '.exe' if necessary */
      |                                    ^~~~~~
mainv1.c:158:82: warning: implicit declaration of function '_wtoi' [-Wimplicit-function-declaration]
  158 |         return ( GetEnvironmentVariableW( L"QPREXITCODE", bufW, MAX_PATH + 1 ) ? _wtoi( bufW ) : exitcode );
      |                                                                                  ^~~~~
mainv1.c:200:82: warning: pointer/integer type mismatch in conditional expression
  200 |     CreateProcessW( pwsh_pathW, !( (i == argc ) && !read_from_stdin ) ? cmdlineW : wcscat( wcscat ( wcscat( wcscat( wcscat( \
      |                                                                                  ^
/usr/bin/ld: cannot find -lurlmon: No such file or directory
/usr/bin/ld: cannot find -lshlwapi: No such file or directory
/usr/bin/ld: cannot find -ladvapi32: No such file or directory
/usr/bin/ld: cannot find -luser32: No such file or directory
/usr/bin/ld: cannot find -lwinecrt0: No such file or directory
/usr/bin/ld: cannot find -lkernel32: No such file or directory
/usr/bin/ld: cannot find -lntdll: No such file or directory
collect2: error: ld returned 1 exit status
winegcc: /usr/bin/gcc failed

**Comment by PietJankbal** [comment]
Hi there,

You can find the exe's in the release section:
 https://github.com/PietJankbal/Chocolatey-for-wine/releases/tag/v0.5o.703

Further , if you want to compile yourself, you have to use mingw; winegcc is not really supported to compile

Regards

**Comment by PietJankbal** [comment]
Hi, I close this as compiling with winegcc is not supported, ok?

Regards

**Comment by PietJankbal** [comment]
closing
